=== karv/Civ/Civ/Data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="g_Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ciencias"/>
        <xs:element ref="Recursos"/>
        <xs:element name="RecursoAlimento" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Ciencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ciencia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Ciencia">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element ref="RecursoReq"/>
        <xs:element name="CantidadReq" type="xs:decimal"/>
        <xs:element name="ReqCiencia" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="RecursoReq">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Recursos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Recurso" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Recurso">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Nombre" type="xs:string"/>
        <xs:element name="Desaparece" type="xs:boolean" minOccurs="0" default="false"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== karv/Civ/Civ/Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<g_Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Data.xsd">
  <Ciencias>
    <Ciencia>
      <Nombre>Lenguaje</Nombre>
      <RecursoReq>
        <Nombre>Ciencia</Nombre>
      </RecursoReq>
      <CantidadReq>500</CantidadReq>
      <ReqCiencia></ReqCiencia>
    </Ciencia>
  </Ciencias>
   <Recursos>
    <Recurso>
      <Nombre>Ciencia</Nombre>
      <Desaparece>true</Desaparece>
    </Recurso>
    <Recurso>
      <Nombre>Alimento</Nombre>
      <Desaparece>false</Desaparece>
    </Recurso>
  </Recursos>
  <RecursoAlimento>Alimento</RecursoAlimento>
</g_Data>
